### ISSUE TITLE
There is no Jenkins resources now

### ISSUE THREAD

**Issue by saeinc** [microsoft/MCW-OSS-PaaS-and-DevOps#44]
I couldn't find Jenkins resource in Azure Portal. 
Is there any other way to replace this resource?

**Comment by timahenning** [comment]
Hi @saeinc ,

Can you provide a little more information?  What exercise and task were you working on?  Do you have a screenshot?

Thanks

**Comment by kylebunting** [comment]
@saeinc, it definitely looks like the marketplace option used in the lab is no longer available.

I'd have to test through things, but you should be able to use any Jenkins server, so perhaps look at using the `Jenkins Container Image` by Bitnami? It's very possible the steps to set things up will be slightly different but should be pretty similar.

Regards,
Kyle

**Comment by kylebunting** [comment]
@DawnmarieDesJardins, just FYI, the Jenkins resource in the Azure Marketplace is no longer available. This is not something that can be fixed in a short amount of time, as we will need to determine what new resource to use and then update all of the steps to accommodate the change. Given that this workshop is being retired, I am not sure we are going to do anything to address this issue, and if so, I'd recommend it be closed with the reason given that the lab is being retired.

**Comment by DawnmarieDesJardins** [comment]
@kylebunting 
Agree on not fixing the issue as we are retiring the workshop in two weeks.  I suggest leaving the issue open until it's retired as you have a possible solution listed above.  If someone wants to work through the workshop before we retire it, I'd like them to see this conversation.  Thoughts?

**Comment by kylebunting** [comment]
@DawnmarieDesJardins, that makes sense to me.

**Comment by DawnmarieDesJardins** [comment]
Closing issues, this workshop is being archived
